### ISSUE TITLE
task `simhash-matching` maybe lost `Figure1` ?

### ISSUE THREAD

**Issue by KKould** [yingfeng/competitive-programming#1]
![image](https://github.com/infiniflow/coding-tasks/assets/91525956/66d8db0f-a492-433c-93b7-6463bf1cf89e)

**Comment by yingfeng** [comment]
Thank you. Fixed by commit [7ea29df](https://github.com/infiniflow/coding-tasks/commit/7ea29df71bcd95f09173023dd891734dc661a04d)
